### ISSUE TITLE
Figure out how/what to polish X-Ray Goggles

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.mozilla.org#1184]
Moving the goggles to a new domain is fairly straight forward, but some things are going to need care:
- [ ] figure out where the landing and install pages need to live. https://github.com/mozilla/teach.mozilla.org/issues/1294
- [x] login is a biggie: if we need to use id.wmo people would navigate off of the page they're on, unless we do id.wmo inside an iframe. @jbuck may need to help think about how to tackle this
- [x] publishing will no longer be "as a make", but straight to S3, if we're retiring the MakeAPI
- [ ] make sure automatic deployment works https://github.com/mozilla/teach.mozilla.org/issues/1295

If we're retiring the MakeAPI and makes gallery, then we also need a place where goggles makes can be "viewed" either for everyone, or at least for people who published them to revisit (at least: open up, not edit).
- [ ] Where will this gallery live - part of the future services discussion 
- [ ] how cross-tool will this be? (goggles and thimbles again?) - part of the future services discussion 

banners content:
- [ ] we need some new copy to drop in the banner going forward https://github.com/mozilla/teach.mozilla.org/issues/1224
- [ ] we can update anything that we publish "from now on". https://github.com/mozilla/teach.mozilla.org/issues/1224
- [ ] retroactively updating all the old goggles publications is, practically speaking, impossible due to needing to read and process every individual published document in the goggles S3 bucket. - we will not do this
- [ ] adding in the "what are we remixing from" should be detectable, and so we can probably work that url in when a goggles remix is published. - part of the rewrite PR

**Comment by Pomax** [comment]
crosslinking these:

- https://github.com/MozillaFoundation/plan/issues/508
- https://github.com/MozillaFoundation/plan/issues/528
- https://github.com/MozillaFoundation/plan/issues/529

**Comment by Pomax** [comment]
Moving the goggles to a new domain is fairly straight forward, but some things are going to need care:
- [ ] login is a biggie: if we need to use id.wmo people would navigate off of the page they're on, unless we do id.wmo inside an iframe. @jbuck may need to help think about how to tackle this
- [ ] publishing will no longer be "as a make", but straight to S3, if we're retiring the MakeAPI

**Comment by jbuck** [comment]
* integrating goggles with id.wm.o will be difficult, but not impossible.
* use [https://github.com/mozilla/publish.webmaker.org](publish) for publishing content. It's what Bramble uses. Talk to us if it doesn't work, because it should totally work for your use case
* Bramble created their own gallery for the MVP. I'd suggest doing the same, or figure out the bare minimum of work to create a gallery for publish.wm.o that can be shared between bramble and goggles
* I wouldn't worry about older content. We're going to continue to host content on makes.org, so people can remix it into the "new" goggles

@Pomax can you please come up with a codename to distinguish goggles on webmaker and whatever we end up calling this? :dancers:

**Comment by hannahkane** [comment]
obviously, the codename is boggles :)

**Comment by Pomax** [comment]
I'm voting for "giggles"

**Comment by Pomax** [comment]
Realistically, for the Sept 11th heartbeat I'm focussing on getting new login and *hopefully* publish.wmo interfacing to work

**Comment by hannahkane** [comment]
@Pomax - do you want to keep this ticket open as an organizing ticket, or are you okay to close since all of the specific tasks have been filed separately?

**Comment by Pomax** [comment]
Let's keep it around: I've moved all the checkbox items to the first comment, so that github treats it as a tracking issue now too (it'll show *x/10* to track completion status this way)

**Comment by hannahkane** [comment]
K. Moving it to current heartbeat then.

**Comment by hannahkane** [comment]
@Pomax to close this ticket once everything is accounted for in other tickets

**Comment by Pomax** [comment]
new issues filed, closing this one.
