### ISSUE TITLE
Clubs Report Module meta ticket

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.mozilla.org#1357]
### Background ###
We have wireframes for the Clubs Report feature, as part of the larger [MLN Directory](https://redpen.io/p/ve944daa8712303367) work. We have an immediate need for the Clubs Report feature—collecting information from Club Captains about how their Club activities are going is critical to the current phase of Clubs program development. Let's separate out the Reports feature from the rest of the Directory. 

### Phases of this work ###
 - [ ] [Revise Event Report wireframes based on most recent feedback; eliminate dependency on having a Group page](#1417) - Nov 20
 - [x] Collect feedback from RCs and Club Captains on wireframes (@amirad - is this something you can coordinate) (at MozFest?)
 - [ ] Provide design comps (December 4th heartbeat)
 - [ ] Implement reporting feature and data storage / access (e.g. staff should be able to review reports when they are submitted) (December 18th heartbeat; possible blocker: Orlando work week)
 - [ ] Test with current Club Captains (early 2016)

**Comment by amirad** [comment]
Are the wireframes ready for feedback now? I am happy to send them out for feedback if so.

**Comment by hannahkane** [comment]
Good question, @amirad. I was thinking we would spend time refining them because the way they are now they depend on having fancy Club pages, but I suppose if we just want feedback on the content of the reports themselves, we can go ahead with what we have. So, yeah, let's go ahead and get feedback. Let me know how I can help!

**Comment by amirad** [comment]
Just flagging that we have a call on Nov 3rd with RCs and will make sure to add these in there for feedback. @hannahkane  - it's 11am ET so might be too early for you but let me know if there is a specific list of questions I can ask them.

**Comment by hannahkane** [comment]
Hmm...might be able to make it, but should probably be heading to the airport around that time. @sabrinang - could you drop in a link to wireframes that Amira could share with the RCs next week?

**Comment by amirad** [comment]
OMG... @hannahkane  it's okay if you can't! Just a link to the wireframes and maybe a couple leading questions you think would be valuable and we can gather the info for you.

**Comment by sabrinang** [comment]
The research slide deck starting on slide 11: https://docs.google.com/presentation/d/19haCbs4KAQnmpItgg-VPwa-ehvrgX139Ycw2h88BiIs/edit#slide=id.gbce6b6c13_0_56
has the most up to date wireframes on slides

**Comment by amirad** [comment]
I'm assuming the most related wireframe would be that on slide 21? Is there any way to get a link to just that image since it's hard to see on the slide? @sabrinang

**Comment by hannahkane** [comment]
Ping @sabrinang to make sure @amirad has what she needs to collect feedback. Thanks!

**Comment by amirad** [comment]
hey @sabrinang @hannahkane the call is in an hour so will either gather quick feedback without images or hopefully get some questions/images from you before then!

**Comment by amirad** [comment]
@hannahkane  lots of feedback on the reporting system in the etherpad https://public.etherpad-mozilla.org/p/teach.clubs-rccalls (I have also emailed those who couldn't attend to go back and add feedback). 

Also some people accidentally commented straight into the design here: https://redpen.io/gxa2e0bf3339a41de1

**Comment by hannahkane** [comment]
@amirad - this is such good feedback! will be super helpful as we finalize and implement a v1. Thanks so much for collecting this!

**Comment by hannahkane** [comment]
Closing, as we'll likely approach this differently, given CC feedback.
