### ISSUE TITLE
rewrite React components to modern form

### ISSUE THREAD

**Issue by Pomax** [mozilla/teach.mozilla.org#1550]
- [x] [change Mixins to HOC](https://github.com/mozilla/teach.mozilla.org/issues/1553)
- [x] [remove use of experimental `context`](https://github.com/mozilla/teach.mozilla.org/issues/1551)
- [x] [change how pages identify themselves (defaultProps)](https://github.com/mozilla/teach.mozilla.org/issues/1552)
