### ISSUE TITLE
change Mixins to HOC

### ISSUE THREAD

**Issue by Pomax** [mozilla/teach.mozilla.org#1553]
Switch all our mixins over to HOC (decorator-style) code instead. See https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750

- [x] [anchor-manager.js](https://github.com/mozilla/teach.mozilla.org/issues/1554)
- [x] [modal-manager.js](https://github.com/mozilla/teach.mozilla.org/issues/1555)
- [x] [teach-api-client.js](https://github.com/mozilla/teach.mozilla.org/issues/1556)

**Comment by Pomax** [comment]
:boom:
