### ISSUE TITLE
Create collaboration case studies

### ISSUE THREAD

**Issue by flukeout** [mozilla/teach.mozilla.org#1620]
Collaboration is important to the various teams that create content internally at the foundation. Whatever content management platforms or systems  we will create need to account for this. In order to do this effectively, we need to learn about how our teams collaborate. With that in mind, we've identified four teams to create case studies about...

**Teams**
* Participation Team
  * What do they create?
* Science Team
  * Workshop handouts
* Clubs Team
  * Guides & templates
* Curriculum Team
  * Teaching material
* The Community
  * ...?

**Questions**
For each of these groups, we let's find out..

* What tools do they use to create content
* What tools do they use to collaborate
* Who do they collaborate with
* At what stage of the project
* What form does the collaboration take?
  * Real time co-authoring?
  * Feedback and suggestions?
  * etc.
* What's working well?
* What's not working well?
* Is needing to know HTML an impediment to collaboration and attracting collaborators?
* Any other technical barriers?
* ... others questions?

**To-do**
* [x] Identify members from each team or group to talk to
* [x] Decide on format for collecting data
  * [x] Google form?
  * [ ] In-person interviews?
*  [x] Write the questions

cc @hannahkane Did I miss anything?

**Comment by hannahkane** [comment]
@flukeout - above list looks great. Emma, Zannah, Amira, and Chad would be good people to start with. And each of them could probably refer us to community members to talk to. I can help with creating a Google form or conducting interviews.

**Comment by flukeout** [comment]
@hannahkane I've wrote a [draft of the questions](https://docs.google.com/document/d/1-rEkboCWEntoDKtorurxo2r-blBOga1G59pQZIWHywA/edit) - please have a look and let me know what you think and I'll convert it to a Google Form.

**Comment by hannahkane** [comment]
Thanks, @flukeout. I added some comments. Maybe it's because I've been asked to complete several surveys recently, but I'm feeling a desire to simplify this even more. Fewer open ended questions? Maybe just reduce the number of questions?

**Comment by flukeout** [comment]
Thanks @hannahkane, will look over your notes.

**Comment by flukeout** [comment]
Editable survey lives here...
https://docs.google.com/a/mozillafoundation.org/forms/d/1a2j3cwNCJPq2BTEqKBsfL8zcUVIJh0Av8hBvrkPccpE/edit?usp=forms_home&ths=true

This is the shareable link http://goo.gl/forms/w2wfhSCMOH

@hannahkane Can you take a look and see if we're missing anything important? If not, let's get a couple of folks to fill it out before we ask the teams we identified earlier.

**Comment by hannahkane** [comment]
Thanks, @flukeout. I just filled it out for real to see what it felt like. Two of the range questions were kind of hard for me to answer.

"I want to see who last made changes to each part of the content I'm working on collaboratively." - couldn't tell if this was about seeing just the *last* person's changes, or more generally being able to see a history of edits. Possibly rephrase as: "I want to see a history of edits, and be able to revert to older versions."

"I want to see a history of changes made by specific collaborators to content that we are working on together." - couldn't tell if this was about wanting to be able to select a particular collaborator and see what contributions they'd made, or just see a history of all changes. If it's the latter, it seems too similar to the above question.

**Comment by flukeout** [comment]
Thanks for reviewing @hannahkane 

**Question 1**
For "I want to see who last made changes to each part of the content I'm working on collaboratively." I wanted to see if it's important for the person to see exactly who authored what part of the content, kind of like Etherpad allows you to see via the color-coding.

Rephrase to...
* "I want to see who made specific changes to the content. For example, who added this paragraph or changed this link?"

**Question 2**
This was more about seeing a history of changes made by a particular collaborator, but that's more of a question of keeping a history in general, and less about collaboration. I vote we remove this question.

Let me know your thoughts on the rephrasing of Q1 and ditching Q2.

**Comment by hannahkane** [comment]
Your rephrasing of Question 1 is much clearer. Regarding question 2: I forget, is there another question about history? Seems good to include a question about that.

**Comment by flukeout** [comment]
Okay, I'll include Question 2 - it's our only question about history.

**Comment by flukeout** [comment]
@hannahkane I updated the survey based on the feedback discussed above. I think we're ready to send it out. Can you help with the list below? Who in the community might be contributing to CMS-based docs?

**Teams**
* Participation Team
  * Emma
* Science Team
  * Zannah
* Clubs Team
  * Amira, Andre
* Curriculum Team
  * Chad
* The Community
  * ...?

**Comment by flukeout** [comment]
I sent out the survey to the names listed above, you should be cc'd @hannahkane - if we can figure out one or two community members to ask, that would be great!

**Comment by hannahkane** [comment]
@flukeout - I added a few people (staff and community) to the comment above

**Comment by flukeout** [comment]
Thanks!

**Comment by ldecoursy** [comment]
@flukeout Yes to Meredith at Mouse

**Comment by flukeout** [comment]
@soapdog Hey Andre, have you had a chance to fill out the survey I linked above? I didn't see your name in an answer for the first question, so I can't tell.

**Comment by flukeout** [comment]
**Summarized Findings**

* Most people collaborate either **every day** or **a few times a month**
* The most common form of content that is worked on collaboratively is **curriculum**
* Respondents collaborate with both **staff & community members** 
* All respondents collaborate with groups of no more than **5 people**
* Collaboration happens at **all stages of content creation** including, planning, drafting & revising after publish
* The most common platforms for collaboration are **Google Docs, Etherpad & Github**
* One of the hardest things about effective collaboration is **the skill level needed to use various tools**
* **Real-time** collaboration is very important to most respondents
* **Commenting** on collaboratively edited content is important
* The ability to *see who changed what** is moderately important
* A **history of changes by each contributor** is not an important feature 
* Respondents want to be **notified when collaborators make changes** to a shared document
* **Fine-grained permissions** are important
* Most respondents wanted to **approve edits on live content** made by collaborators

**Further questions**
* I would like to figure out what some different workflows for collaboration are, and how often they happen. Do they require different features or approaches?
  *  Someone starts a document by creating a draft and _then_ invites collaborators
  * A document is started in real-time from scratch by a few people
* I would like to figure out what needs someone has as the original author & owner of a document versus a contributor who is invited to edit.
  * I think most of our questions were geared towards the person starting a collaborative project, but people who are invited into a project might have different needs & perspectives.
  * How to collaborators like to be invited?
  * How do authors like to invite people? 
* Should find out more specifically if people want the "approve this edit" feature when a collaborator makes a change.

**Overall Feeling**
In general, it feels like the most important features are...
* **Real-time** collaborative editing
* Ability to **leave comments** 
* Make the editing experience as easy and barrier-free as possible. Barriers could include...
  * Complicated UI
  * Need for an account

**Comment by hannahkane** [comment]
great summary, @flukeout. Thanks for doing this.

Your next steps look good. I definitely think we should audit the relevant Calypso features and assess what gaps we'll have. As part of that, though, I'm curious whether you think Calypso needs to solve all of the collaboration needs, or if people can continue to use gDocs, etherpad, and github for some of them (e.g. real-time collaborative editing).

**Comment by flukeout** [comment]
Good question @hannahkane - I think the collaboration features will affect how calypso is used, maybe if it has real-time collaboration, people would skip the etherpad/google doc step? My feeling is that we'll just have to kind of "wait and see" - calypso offers a whole new authorship paradigm for our org, so let's just keep tabs on the emerging behaviours and needs, it's hard to predict! If we see people sticking with Google Docs & Etherpad as a way to publish content for others because of the real-time collaboration, we'll know it's a missing piece of calypso.

**Comment by hannahkane** [comment]
+1 to seeing how the presence of Calypso changes people's workflows and +1 to seeing what needs emerge

**Comment by hannahkane** [comment]
@flukeout - do you think we can close this ticket and file follow-ups as needed?

**Comment by flukeout** [comment]
I've filed a couple of follow-up issues...

* #1741 - Exploring & documenting existing calypso collaboration features.
* #1742 - Mapping out some collaboration workflows from different perspectives.

I wonder too, if we should set up some kind of 'test collaboration scenario' and ask a couple of people to participate in a sort of fake real-world case-study. I'm not sure - let's chat in stand @hannahkane ?

**Comment by hannahkane** [comment]
Definitely want to hear more about the fake case study - not sure I understand what you mean by that.
OK to close the ticket in the meantime, since follow-ups are filed?

**Comment by hannahkane** [comment]
@flukeout - I'm closing this since the follow-ups have been filed.
