### ISSUE TITLE
Forge a QA checklist

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.mozilla.org#806]
During the stand today we discussed the QA process of how exactly we want to go from staging (develop branch) to production (master branch). Currently, for instance, we have PR #805 which is a request to merge changes from develop into master.

We decided that it'd be useful to have a QA checklist of things to do before pushing to production. It can include:

- [ ] Does the site work properly on our [supported browsers](https://github.com/mozilla/teach.webmaker.org/issues/151)?
- [ ] Is the site accessible?
- [ ] It'd be nice to have a suite of integration tests to run on staging that could ensure that all the parts (teach, teach-api, id.webmaker.org, etc). work together properly. Alternatively, we could just have manual tests, or a combination of both.

(The above list will be updated as we come up with new requirements.)

Also, @gesa mentioned another Mozilla program that (I think?) empowers community to help us with QA. This would be awesome to make use of, if we could just remember the name.

**Comment by toolness** [comment]
@hannahkane, we should probably figure out a process for this soon, as #805 is building up lots of changes fast!

**Comment by toolness** [comment]
It looks like this page in the MoFo Engineering Handbook has some good information:

https://github.com/MozillaFoundation/MoFo-Engineering-Handbook/blob/master/onboarding/preflight.md

**Comment by hannahkane** [comment]
I'm planning to start including acceptance tests on all tickets that represent user stories (that is, big chunks of UX), so I would add to the checklist that all acceptance tests pass.

**Comment by toolness** [comment]
Whoa cool!

Hannah have you ever heard of a thing called [Cucumber](https://cukes.info/)? It's almost more of a communication/workflow tool than a software development tool--basically allowing stakeholders to communicate requirements to devs, who can actually write tests against them. I thought it would be a neat thing to try out sometime but never found any teams interested enough in trying it out.

**Comment by hannahkane** [comment]
Cucumber looks cool. I'd be down to try it!

**Comment by hannahkane** [comment]
@toolness - what do you think we need to do to close this ticket?

**Comment by toolness** [comment]
Hey @rossbruniges, do you have any thoughts on this one? Do you use any QA checklists that you like, or do you know of any good best practices?

**Comment by rossbruniges** [comment]
BDD (Cucumber) is cool but it's difficult to hook into unless original requirements tickets are written along those specific guidelines.

Things that always used to bite me when deploying:

* brinding dev data and settings over accidentally - if you've gone 12 Factor then I'm sure you're good with this
** if you're using browserID for login then if the site urls in it's config don't match the live URLs then it won't log you in and just look confusing as users get bounced back to the homepage (this bit us briefly when launching source.opennews, this was because dev was http and live was https)
* pre-flight any live caches so that it's ready for when the real users hit
* https certs - make sure that they're all in place and valid
* broken links - there will always be one no matter how many checks you think are in place - should be plenty of automated checkers out there
* favicon (this always gets forgotten)

Am assuming that during development you're already running things through various tests for accessibility (https://tenon.io/) and performance and page weight (https://developers.google.com/speed/pagespeed/insights/).

Another thing that's good to have around - someone who isn't working on the Mozilla network, just to make sure that everything is correctly set up and externally availiable. (I once launched a site, thought it was all good then someone told me the server wasn't connecting - you can guess why).

Other than that if the tests pass then you should be good, when is the go-live date?

**Comment by toolness** [comment]
Whoa, thanks Ross! I didn't actually know about Tenon or PageSpeed Insights, they're really cool.

I've added some notes regarding them to [CONTRIBUTING.md](https://github.com/mozilla/teach.webmaker.org/blob/develop/CONTRIBUTING.md):

> ### Diagnostics
>
> For any pages you've added or changed, make sure you
use [PageSpeed Insights][] to ensure the page is fast on all
devices, and use [Tenon][] to ensure it's accessible.
>
> You can conveniently run any of these tools on the current page
by clicking the "Dev Version" ribbon at the top-right of any
page on the site.

This is what the buttons look like on the Dev Version modal:

![2015-05-15_7-37-16](https://cloud.githubusercontent.com/assets/124687/7652027/59cbf98e-fad5-11e4-8657-4245b635d3fe.jpg)

Those diagnostic buttons are also accessible on the [Manual Tests](https://teach.mofostaging.net/test/manual/) page for every major route:

![2015-05-15_7-38-53](https://cloud.githubusercontent.com/assets/124687/7652035/80a825b4-fad5-11e4-838c-26df478dbdde.jpg)

I've also added a little hostname check so that when you click on one of the buttons from a private IP address or hostname, it guides you to install [ngrok](http://ngrok.com/) so the diagnostic tool can access it:

![2015-05-15_7-32-02](https://cloud.githubusercontent.com/assets/124687/7651987/bb421f28-fad4-11e4-819b-ac2caff53cbc.jpg)

Speaking of ngrok, I also added a section to the contributing file about using it to easily check for Mixed Content warnings (thanks to @k88hudson for suggesting this):

> ### HTTPS
>
> We often develop using http, but the production site is always
hosted via https. Consider using a tool like [ngrok][] to easily
tunnel into your local server over https to ensure that your
changes haven't introduced any [Mixed Content][] warnings.

[ngrok]: https://ngrok.com/
[Mixed Content]: https://developer.mozilla.org/en-US/docs/Security/MixedContent
[PageSpeed Insights]: https://developers.google.com/speed/pagespeed/insights/
[Tenon]: http://tenon.io/

**Comment by toolness** [comment]
Oh, and we added a link checker to our automated test suite in #809, but it only checks to ensure that *internal* links are working. We're also using route names with react-router's [`Link`](http://rackt.github.io/react-router/#Link) component, which is a bit like Django's [`{% url %}`](https://docs.djangoproject.com/en/1.8/ref/templates/builtins/#std:templatetag-url), so it also helps ensure that internal links aren't broken.

We should probably add a link checker that spiders out to external links to make sure they don't 404, though--I'm just not sure if we should only run those through Travis since they're likely to slow down the test suite, and we want to keep test suites running fast so that devs actually use them!

**Comment by toolness** [comment]
So while it's not quite the same thing as a QA checklist, I am updating our [`CONTRIBUTING.md`](https://github.com/mozilla/teach.webmaker.org/blob/develop/CONTRIBUTING.md) with information on things that we've frequently forgotten about (accessibility, image size, etc). Still not really sure when our QA checklist will be "definitive" or "complete" though, hmm.

**Comment by rossbruniges** [comment]
Very awesome!!

**Comment by toolness** [comment]
Thanks! I also just added notes about how to test for browsers that don't support HTML5 form validation in 69f398ba22861ed2a4e525a9257743a9bcdda070.

**Comment by hannahkane** [comment]
@toolness - should we roll this ticket into the next heartbeat?

**Comment by hannahkane** [comment]
@toolness - how are you feeling about this ticket? I'd rather not keep rolling it into the next heartbeat, unless you think it's necessary.
